# SPDX-License-Identifier: GPL-3.0-or-later
#
# AstropathDNSRelay — self-hosted ACME DNS-01 solver gateway.
# Copyright (C) 2026  Saad Ali
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

"""m2 baseline schema (revision 1, SPEC §12.1).

The DB-landing baseline: ``alembic upgrade head`` builds the whole M2 schema on an
empty database. For a pre-existing ``create_all`` DB, ``alembic stamp head``
records this revision without re-running DDL. All later changes ship as new
revisions.

Revision ID: 0001
Revises:
Create Date: 2026-07-06 22:05:49.297155
"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0001"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "admincredential",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("password_hash", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "apitoken",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("token_hash", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_used_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_apitoken_name"), "apitoken", ["name"], unique=False)
    op.create_index(
        op.f("ix_apitoken_token_hash"), "apitoken", ["token_hash"], unique=True
    )
    op.create_table(
        "backend",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("type", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("config_encrypted", sa.LargeBinary(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_backend_name"), "backend", ["name"], unique=True)
    op.create_index(op.f("ix_backend_type"), "backend", ["type"], unique=False)
    op.create_table(
        "tsigkey",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("algorithm", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("secret_encrypted", sa.LargeBinary(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_tsigkey_name"), "tsigkey", ["name"], unique=True)
    op.create_table(
        "challengeevent",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("ts", sa.DateTime(timezone=True), nullable=False),
        sa.Column("zone", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("record_name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("action", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("provider", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("result", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("latency_ms", sa.Integer(), nullable=False),
        sa.Column("tsig_key_id", sa.Integer(), nullable=True),
        sa.Column("source", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("error_detail", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.ForeignKeyConstraint(["tsig_key_id"], ["tsigkey.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_challengeevent_tsig_key_id"),
        "challengeevent",
        ["tsig_key_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_challengeevent_zone"), "challengeevent", ["zone"], unique=False
    )
    op.create_table(
        "domain",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("zone", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("backend_id", sa.Integer(), nullable=False),
        sa.Column("record_name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("secret_encrypted", sa.LargeBinary(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["backend_id"],
            ["backend.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_domain_backend_id"), "domain", ["backend_id"], unique=False
    )
    op.create_index(op.f("ix_domain_zone"), "domain", ["zone"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_domain_zone"), table_name="domain")
    op.drop_index(op.f("ix_domain_backend_id"), table_name="domain")
    op.drop_table("domain")
    op.drop_index(op.f("ix_challengeevent_zone"), table_name="challengeevent")
    op.drop_index(op.f("ix_challengeevent_tsig_key_id"), table_name="challengeevent")
    op.drop_table("challengeevent")
    op.drop_index(op.f("ix_tsigkey_name"), table_name="tsigkey")
    op.drop_table("tsigkey")
    op.drop_index(op.f("ix_backend_type"), table_name="backend")
    op.drop_index(op.f("ix_backend_name"), table_name="backend")
    op.drop_table("backend")
    op.drop_index(op.f("ix_apitoken_token_hash"), table_name="apitoken")
    op.drop_index(op.f("ix_apitoken_name"), table_name="apitoken")
    op.drop_table("apitoken")
    op.drop_table("admincredential")
    # ### end Alembic commands ###
